Update Swift 5
yoomoney/functional-swift pull request #11
Opened 2019-07-16 18:00 UTC by oltv00

2019-07-17 14:17 UTC, anukhov submitted a review, later dismissed

2019-07-18 09:56 UTC, MetalheadSanya requested changes

2019-07-18 09:56 UTC, MetalheadSanya commented on FunctionalSwift.xcodeproj/project.pbxproj
> +				Base,
Кажется локализация должна в итоге быть только Base

2019-07-18 10:04 UTC, oltv00 commented on FunctionalSwift.xcodeproj/project.pbxproj
> +				Base,
Возможно.
Убрал, лишнее, вроде все работает

2019-07-18 10:05 UTC, MetalheadSanya approved these changes

2019-07-18 10:05 UTC, merged