add splitPlaces method for collection
yoomoney/functional-swift pull request #7
Opened 2018-03-07 13:59 UTC by alexdonduk

2018-03-07 14:14 UTC, MetalheadSanya requested changes

2018-03-07 14:14 UTC, MetalheadSanya commented on FunctionalSwift/Collection/Collection+Split.swift
> +    public func splitPlaces(_ places: [Int]) -> [SubSequence] {
Нужно переименовать метод в соответствии с другими методави в этом файле. `splitPlaces(_:)` -> `split(places:)` .

2018-03-07 14:23 UTC, MetalheadSanya commented
Так же необходимо аоднять версию в podspec

2018-03-07 15:00 UTC, MetalheadSanya requested changes
Отписал правки в комметариях

2018-03-12 10:57 UTC, alexdonduk commented on FunctionalSwift/Collection/Collection+Split.swift
> +    public func splitPlaces(_ places: [Int]) -> [SubSequence] {
fixed

2018-03-12 10:58 UTC, alexdonduk commented
Fixed remarks

2018-03-12 13:08 UTC, MetalheadSanya requested changes

2018-03-12 13:08 UTC, MetalheadSanya commented on FunctionalSwift/Collection/Collection+Split.swift
> +    /// `splitPlaces([])` split a list into chunks of the given lengths.
Документацию надо было бы тоже поправить, а не только имя метода)

2018-03-12 19:07 UTC, aleksandr-romanov commented on FunctionalSwift/Collection/Collection+Split.swift
> +    /// `splitPlaces([])` split a list into chunks of the given lengths.
fixed

2018-03-12 19:25 UTC, MetalheadSanya approved these changes

2018-03-12 19:26 UTC, merged